### ISSUE TITLE
Update code to use plotly 4.0 in dev and prd

### ISSUE THREAD

**Issue by bmewing** [emnBusinessAnalytics/viz-package-comparison#4]
This is a top priority this week so we can finish the upgrade on Shiny server.  If this project doesn't actually need to be updated, that's fine, comment as such and close.

Documentation at plot.ly/r/ is up to date and this article provides details
http://moderndata.plot.ly/upgrading-to-plotly-4-0-and-above/

**Comment by AdamSpannbauer** [comment]
Plotly update not needed for this project.  Repo is a one time report.
